<div class="panel-body">
  <ul class="nav nav-pills">
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/antiques/">Antiques</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/art/">Art</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/baby/">Baby</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/books/">Books</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/industrial/">Business &amp; Industrial</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/photography/">Cameras &amp; Photo</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/cell_phones/">Cell Phones &amp; PDAs</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/clothing/">Clothing, Shoes &amp; Accessories</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/coins/">Coins &amp; Paper Money</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/collectibles/">Collectibles</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/computers/">Computers &amp; Networking</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/crafts/">Crafts</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/dolls/">Dolls &amp; Bears</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/dvd/">DVDs &amp; Movies</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/motors/">eBay Motors</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/electronics/">Electronics</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/entertainment_memorabilia/">Entertainment Memorabilia</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/gift_certificates/">Gift Certificates</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/health_beauty/">Health &amp; Beauty</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/home/">Home &amp; Garden</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/jewelry/">Jewelry &amp; Watches</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/music/">Music</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/instruments/">Musical Instruments</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/pet_supplies/">Pet Supplies</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/pottery_glass/">Pottery &amp; Glass</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/realestate/">Real Estate</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/services/">Specialty Services</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/sporting_goods/">Sporting Goods</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/sports_cards/">Sports Mem, Cards &amp; Fan Shop</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/stamps/">Stamps</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/tickets/">Tickets</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/toys/">Toys &amp; Hobbies</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/travel/">Travel</a></li>
    <li><a href="<?  echo $path ?>/<?php echo $country; ?>/video_games/">Video Games</a></li>
  </ul>
</div>
